New add colloid method
SwarmRL/SwarmRL pull request #13
Opened 2023-03-28 14:18 UTC by Koppeprojects

To the current state it is nor easily possible to place colloids one by one on precise places and orientations. This pull request adds a method for this and rewrites the original way of adding colloids. Be sure to only add colloids one by one if no existing colloid type is given a new radius. Is this condition reasonable. It is there to be compatible with existing colloid radius handling.

2023-03-28 16:47 UTC, christophlohrmann requested changes
looks good. small comment and we can merge

2023-03-28 16:47 UTC, christophlohrmann commented on swarmrl/engine/espresso.py
> +def _angles_from_vector(director):
move this to utils

2023-03-28 16:47 UTC, christophlohrmann commented on swarmrl/engine/espresso.py
> +def _angles_from_vector(director):
the random angles, to

2023-03-28 21:25 UTC, SamTov submitted a review, later dismissed
I think it looks good and have no additional comments to Christoph.

2023-04-13 15:58 UTC, christophlohrmann commented
@Koppeprojects can you fix the formatting so we can merge? This is a nice PR, let's not let it go stale

2023-04-13 15:58 UTC, christophlohrmann approved these changes

2023-04-13 17:09 UTC, christophlohrmann approved these changes

2023-04-13 18:22 UTC, merged