Koppe add maze
SwarmRL/SwarmRL pull request #14
Opened 2023-03-28 14:31 UTC by Koppeprojects

Added a method to easily add constrains that form a maze in the simulation in 2D. Added a simple test for it.

2023-03-28 17:00 UTC, christophlohrmann requested changes

2023-03-28 21:28 UTC, SamTov approved these changes
I think Christoph has hit everything here. I don't see anything more I can add, looks good.

2023-03-30 11:20 UTC, Koppeprojects commented on swarmrl/engine/espresso.py
> +            norm = np.linalg.norm(a)  # is also the norm of b
The comments hopefully make the code more understandable. In the comments I try to make clear which vector point in which direction in respect to the wall

2023-03-30 11:22 UTC, Koppeprojects commented on swarmrl/engine/espresso.py
> +            norm = np.linalg.norm(a)  # is also the norm of b
normally walls are lengthy so "along it" hopefully makes clear which direction is meant.

2023-04-03 12:54 UTC, christophlohrmann requested changes

2023-04-03 12:54 UTC, christophlohrmann commented on swarmrl/engine/espresso.py
> +        maze_wall_start_point: pint.Quantity,
rename to wall_start_points (endpoints analogously)

2023-04-03 12:54 UTC, christophlohrmann commented on swarmrl/engine/espresso.py
> +        list of lists (len()=2) with wall coordinates
it's probably easier for everyone if this is a (n,2) np.array instead of a list of lists

2023-04-03 12:54 UTC, christophlohrmann commented on swarmrl/engine/espresso.py
> +            and self.colloid_radius_register[maze_type] != 0.0
this line relies on an early abort of the and statement, bcs otherwise we access a key that does not exist in the second line.

2023-04-14 14:32 UTC, christophlohrmann approved these changes

2023-04-14 14:33 UTC, merged