Da zi episodic training
SwarmRL/SwarmRL pull request #29
Opened 2023-07-25 12:56 UTC by Dalouvid

A method to reset the system after each episode. 
It can be activated in the gym by setting the "reset" flag to true. 

#### Summary of additions and changes

* added a reset function in the espresso engine 
* added a test for that

#### How to test this pull request

``` run the tests i guess. 

```

2023-07-26 14:48 UTC, christophlohrmann requested changes
The reset includes a lot of coupling for all functions that add particles and have to remember to store their arguments.
The reset doesn't reset system time nor any part of the trajectory writing.

I am still in favour of handling system resets in the script that sets up the system, i.e. creating a fresh engine after each reset and only reusing the espresso system that's inside the engine

2023-07-31 14:38 UTC, Dalouvid commented
> The reset includes a lot of coupling for all functions that add particles and have to remember to store their arguments. The reset doesn't reset system time nor any part of the trajectory writing.
> 
> I am still in favour of handling system resets in the script that sets up the system, i.e. creating a fresh engine after each reset and only reusing the espresso system that's inside the engine

How about we do it like this until the global variables are gone from espresso?
JN will work on it in the next Espresso Coding day so it is only a matter of time until it is done.
When this is done, we can have a clean way of resetting the system.

2023-08-01 08:28 UTC, SamTov commented
> > The reset includes a lot of coupling for all functions that add particles and have to remember to store their arguments. The reset doesn't reset system time nor any part of the trajectory writing.
> > I am still in favour of handling system resets in the script that sets up the system, i.e. creating a fresh engine after each reset and only reusing the espresso system that's inside the engine
> 
> How about we do it like this until the global variables are gone from espresso? JN will work on it in the next Espresso Coding day so it is only a matter of time until it is done. When this is done, we can have a clean way of resetting the system.

I'm not sure I fully understand the comment here. Do you mean we do it the way @christophlohrmann says or the PR? If you are referring to the PR, then I would be against merging it into the main codebase with the intention of later removing it. In this case, I would suggest that those who need it keep maintaining the branch and use it until there is a permanent solution.

2023-08-01 13:35 UTC, Dalouvid commented
Sounds good. Then I'll close the merge request.

2023-08-01 13:36 UTC, closed without merging